config/routes.rb
Rails.application.routes.draw do

  root 'cover_letter#projects'
   resources :cover_letter, only: [:index]
   resources :download, only: [:pdf]
   get '/projects' => 'cover_letter#projects', :as => 'projects'
   get '/about_me' => 'cover_letter#about_me', :as => 'about_me'
   get '/resume' => 'cover_letter#resume', :as => 'resume'

   get "download/pdf"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cover_letter_controller.rb
class CoverLetterController < ApplicationController

	def projects
	end
end

app/controllers/download_controller.rb
class DownloadController < ApplicationController

	def pdf
    send_file Rails.root.join('private', 'michael_ginalick_resume.pdf'), :type=>"application/pdf", :x_sendfile=>true
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cover_letter_helper.rb
module CoverLetterHelper
end

app/helpers/download_helper.rb
module DownloadHelper
end

app/views/cover_letter/Hi_Enova.html.erb
<section class="columns cover-letter">
	<h1 class="h2 inner content remove-bottom-margin">Hi, Jellyvision</h1>
	<h4>This is a site I made that'll hopefully show I'll be a great fit for the Jr. Developer position you have open.</h4>
	<ul class="project">
		<li class="inner">
			<p class="project-title">let's talk about me</p>
			<p class="cover-column">	
				<span class="blue">I am a software developer.</span> I want to make apps that help make life a bit easier. Apps that will clarify a confusing topic or assist in making an important decision. Software can be the tool that helps you lead a better, more well informed life.
			</p>

			<p class="cover-column">
				<span class="secondary-col">I am not just a developer.</span> I'm a book collector and literature enthusiast. While in high school I thought it would be neat to have a small library and have been on the hunt ever since. Thanks to Amazon, I now close to 300 which doesn't seem like a lot until moving day. They always leave me second guessing what I've done and why I continue to collect more.
			</p>

			<p class="cover-column">
				<span class="purple">I graduated from Dev Bootcamp.</span> I've been involved in technology for a few years, but never found a route that I was truly passionate about. After some thought, I decided to leave my job in St. Louis and take a chance to find something that I can look forward to everyday. 
			</p>

			<p class="cover-column">
				<span class="orange">I enjoy helping others learn.</span> Even after graduating, I’m still involved in the community. I volunteer as a mentor at GDI, and next month I start as a mentor at the StartUp Institute. I believe in helping others and being involved in these communities means a great deal to me. Although at times I feel woefully inadequate to help anyone with code, I always find that I learn a great deal by simply fielding questions or helping with syntax. At my previous job, I led a weekly meeting where I would field questions pertaining to the software the team was using. This often involved live coding, pair programming, and admitting when I didn't have the answer. 
    
			</p>
		</li>
		<li class="inner">
			<p class="project-title">let's talk about Jellyvision</p>
			<p class="cover-column">
				<span class="orange">You guys love what you do, and it shows!</span> Viewing your work it’s obvious why you did so well at this year's Moxie awards. From the blogs to the bios, you love your employees and the feeling is mutual. A clear indicator of this is the quality work your teams produce. Your work is both informative and educational and it’s clear that you have cultivated a culture of continual learning and teamwork.
			</p>
			<p class="cover-column">
				<span class="purple">Learning and growth. </span> I strive to be part of an environment where you’re encouraged to expand your skill set and grow as a developer. Learning is about discovery, curiosity and surrounding yourself with people who encourage these qualities. Your work communicates both. As a Jr. Developer my main goal is to get better at this craft, and you guys give people the support they need to make that happen.
			</p>
			<p class="cover-column">
				<span>When companies look for <span class="orange">Jr Developers,</span> it speaks volumes. The second thing it does is communicate that you understand Rome wasn’t built in a day. Learning takes time, and problem solving takes experience, but with the right foundation and proper guidance, anyone can get better and grow. 
			</p>
			<p class="cover-column">
				<span class="secondary-col">I'd love to be on your team.</span> I read that you want someone that knows how to work on a team, who's willing to listen to feedback, and wants to grow as a developer. Most importantly you want someone who is passionate about developement. As a Jr Developer I could bring a solid understanding of Ruby, Rails, and Javascript, an eagerness to learn, and an affinity for team work. I’m a Jr. Developer, and I would love to be part of your team.   
			</p>
			<p class="cover-column">
				<span class="blue">I'm your guy.</span> Shoot me an <a href="mailto:michael.ginalick@gmail.com">email</a> or give me a call (314-546-1424).
			</p>
		</li>
	</ul>
</section>

app/views/cover_letter/about_me.html.erb
<section id="about" class="inner">
	<h2 class="content title">about me</h2>
	<%= image_tag("iceland_pic.jpeg", alt: 'Iceland Pic', class: "selfie") %>
	<p>
		These are the obligitory things that an about me is suppose to have: I mostly enjoy writing code, adding to my book collection - almost 300 now. My moving days are probably worse than yours. Watching movies - currently in awe of 
		<a href = "http://www.imdb.com/title/tt1935156/"><span class="purple"> Jodorowsky's Dune,</span></a> and like pretty much everyone, I like to travel. That's me in at <a href = "http://en.wikipedia.org/wiki/Gullfoss"><span class= "orange">Gullfoss Falls</span></a> in Iceland.
	</p>
	<p>
		Teaching is also something that I'm very interested in. Currently I volunteer at <span class="blue">GDI</span> and the <span class="purple">The Startup Institute</span>. We cover everything from Ruby, Ruby on Rails, Javascript, to HTML and CSS. These courses range in difficulty and members choose which challenges they'd like to tackle. It's very rewarding to see people come in with varying programming skills, work hard, and have it pay off in the form of making a simple webpage or complete a tricky JS challenge. Although I don't have all the anwsers and often have to sit down and think through the problems right along side the student, I always learn so much from breaking something down, exposing weaknesses in my understanding as well as watching how other people approach problems. Programming is all about learning and they say you don't know it until you can teach it! Hopefully, this helps me better understand the fundamentals. 


	</p>
	<p>
		Whether it be a small web app for your home business or crunching terabytes of data to tackel a complex national policy issue, I'm interested in helping you solve your problem.
	</p>
	<p>
		I love to learn, get better, and think that I'd make a good fit on your team.
	</p>
	<p>
		
	</p>
</section>

app/views/cover_letter/projects.html.erb
<section id="projects" class="columns">
  <h1 class="h2 inner content remove-bottom-margin">projects</h1>
	<ul class="project">
		<li class="inner">
			<p class="project-title"><a href="http://gasulator.herokuapp.com/">  Gasulator</a> <a href="https://github.com/michaelginalick/bespectacled_lampshade">
				<%= image_tag("logos/github-logo.png", alt: 'Github', class: "logo-img") %></a></p>
			<p class="content project-description">A site that helps simplify the process of buying a car by providing a better understanding of the true cost of owning a car. Input your home and work addresses, then choose a vehicle. The app will calculate the round trip commute distance and return a fuel cost by day, month and year.</p><br><br>
			<a class="work-link" href="http://gasulator.herokuapp.com/">
				<div id="twochez" class="project-box">
					<h4 class="project-tag black-scrim">Gasulator</h4>
				</div>
			</a>
		</li>
		<li class="inner">
			<p class="project-title"><a href="http://halfcourtpressdbc.herokuapp.com/">halfCourtPress</a> <a href="https://github.com/michaelginalick/stats_tracker"><%= image_tag("logos/github-logo.png", alt: 'Github', class: "logo-img") %></a></p>
			<p class="content project-description">A basketball educational tool used to collect various types of basketball statistics and display them in a form of a heatmap, giving users, players, and coaches feedback on their frequency. Collect the number of shots made, missed, rebounds, steals, blocks, and turnovers occurred and know the exact position of their occurrence.</p>
			<a class="work-link" href="http://halfcourtpressdbc.herokuapp.com/">
				<div id="first-world-problems" class="project-box">
					<h4 class="project-tag black-scrim">halfCourtPress</h4>
				</div>
			</a>
		</li>
		<li class="inner" id="new_project">
			<p class="project-title"><a href="https://homelibraryapp.herokuapp.com/">HomeLibrary</a> <a href="https://github.com/michaelginalick/libraryapp"><%= image_tag("logos/github-logo.png", alt: 'Github', class: "logo-img") %></a></p>
			<p class="content project-description">An application that allows you to seed your library via a CSV import. Friends can create an account, view all your books, and checkout the ones they like. They will recieve an automated text reminding them when the book is due courtesy of Twillio API. Users can also view the books' Goodreads score and synopsis via the Goodreads API. It also includes an administration side that tracks all book activity.</p>
			<a class="work-link" href="https://homelibraryapp.herokuapp.com/">
				<div id="first-world-problems" class="project-box">
					<h4 class="project-tag black-scrim">HomeLibrary</h4>
				</div>
			</a>
		</li>
		<li class="inner" id="newest_project">
			<p class="project-title"><a href="http://traintimetexts.herokuapp.com/">CTA Tracker</a> <a href="https://github.com/michaelginalick/ctaapp"><%= image_tag("logos/github-logo.png", alt: 'Github', class: "logo-img") %></a></p>
			<p class="content project-description">An application that allows you to pick your train, the times you'll be coming or going, and recieve a text with the chosen train schedule. These notifications run on your fixed schedule so you'll recieve updates per your schedule. User login in, AJAX for creation, and deletion of trains. All CTA lines available for schedule with the help of CTA API. Made with the help of the Twillio API, Nokogiri, Redis, and Sidekiq for job execution.</p>
			<a class="work-link" href="http://traintimetexts.herokuapp.com/">
				<div id="first-world-problems" class="project-box">
					<h4 class="project-tag black-scrim">CTA Tracker</h4>
				</div>
			</a>
		</li>
	</ul>
</section>

app/views/cover_letter/resume.html.erb
<section id="resume" class="content inner">
	
	<h1 class="h3">Michael Ginalick</h1>
	<ul class="contact content remove-top-margin">
		<li>
			<p><span class="blue">email:</span> michael.ginalick@gmail.com</p>
		</li>
		<li>
			<p><span class="blue">phone:</span> 314-546-1424</p>
		</li>
		<li>
			<p><span class="blue">github:</span> <a href="https://github.com/michaelginalick">github.com/michaelginalick</a></p>
		</li>
		<li>
			<p><span class="blue">resume download:</span> <%= link_to 'pdf version', download_pdf_path %></p>
		</li>
	</ul>

	<article class="summary">
		<h2 class="h4 resume-heading content">summary</h2>
		<p class="text-left">
			I care about the technologies I use, understanding that every language and framework have inherent strengths and weaknesses, and they are only as valuable as the team behind them.<br><br>

			I invest in the people around me, teaching each other, and maximizing our potential. Not only to solve the current problems, but also setting up future problems to be easier to solve by writing maintainable, test driven code.
		</p>
	</article>

	<article class="skills">
		<h2 class="h4 resume-heading content">skills</h2>
		<p class="skill">
			<span class="blue">languages:</span> Ruby, Javascript, HTML5, CSS3, VB Script
		</p>
		<p class="skill">
			<span class="blue">web frameworks:</span> Rails, Sinatra
		</p>
		<p class="skill">
			<span class="blue">testing frameworks:</span> Rspec, Jasmine, Capybara
		</p>
		<p class="skill">
			<span class="blue">database:</span> SQL, Activerecord, Oracle, Postgres
		</p>
		<p class="skill">
			<span class="blue">other important things:</span> version/workflow control with git, test- and behavior-driven development
		</p>
	</article>

	<article class="education">
		<h2 class="h4 resume-heading content">education</h2>
		<p class="skill">
			<span class="blue">BS:</span> Information MGMT systems, University of Missouri St. Louis
		</p>
	</article>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Michael Ginalick</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>

  	<title>Michael Ginalick  </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!-- <link rel="icon" href="/assets/images/logos/zp.png"> -->
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,900|Raleway:400,700|Josefin+Slab:400,700' rel='stylesheet' type='text/css'>

<!-- Javascript -->
    
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="/assets/js/main.js"></script>
      <header>
        <div class="contain">
          <nav>
            <ul class="nav social pull-left">
              <li>
                <a href="/">
                  <%= image_tag("logos/mag.png", alt: 'MAG', class: "logo-img") %>
                </a>
              </li>
            </ul>
            <ul class="nav social navbar">
              <li>
                <a class="h6 nav-link blue" href="/projects">projects</a>
              </li>
              <li>
                <a class="h6 nav-link blue" href="/about_me">about me</a>
              </li>
              <li>
                <a class="h6 nav-link blue" href="/resume">resume</a>
              </li>
            </ul>
          </nav>
        </div>
      </header>



</head>
<body>

<%= yield %>

<footer id="footer" class="inner">
	<ul class="nav social">
    <li>
      <a href="https://github.com/michaelginalick">
        <%= image_tag("logos/github-logo.png", alt: 'Github', class: "logo-img") %>
      </a>
    </li>
    <li>
      <a href="https://twitter.com/mginalick">    
        <%= image_tag("logos/twitter-logo.png", alt: 'Twitter', class: "logo-img") %>
      </a>
    </li>
    <li>
      <a href="https://www.linkedin.com/in/michaelginalick">
        <%= image_tag("logos/linkedin.png", alt: 'linkedin', class: "logo-img") %>
      </a>
    </li>
  </ul>
	<ul>
		<li>
			<a class="btn h6" href="mailto:michael.ginalick@gmail.com">let's talk</a>
		</li>
	</ul>
</footer>

</body>
</html>